openapi: 3.0.0
info:
  title: Scam Explorer API
  version: 1.0.0
  description: API for scanning and assessing Ethereum addresses
servers:
  - url: http://localhost:8000
    description: Local server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: []

paths:
  /top-risk-addresses:
    get:
      summary: Get top risk addresses
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    risk_score:
                      type: number

  /address-info/{address}:
    get:
      summary: Get address info
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  risk_score:
                    type: number
                  risk_reason:
                    type: string
                  overall_assessment:
                    type: string
                  total_transactions:
                    type: number
                  total_received:
                    type: number
                  total_sent:
                    type: number
                  current_balance:
                    type: number

  /report-address:
    post:
      summary: Report an address
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                report_reason:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /scan/{address}:
    get:
      summary: Scan an address
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  risk_score:
                    type: number
                  ml_analysis_result:
                    type: string
                  overall_assessment:
                    type: string
                  total_transactions:
                    type: number
                  total_received:
                    type: number
                  total_sent:
                    type: number
                  current_balance:
                    type: number
                  blacklist_category:
                    type: string
                  blacklist_search_result:
                    type: string
                  phishing_dataset_check:
                    type: string
                  transaction_tracing_result:
                    type: string
                  whitelist_search_result:
                    type: string

  /trigger-update:
    post:
      summary: Trigger an update of all addresses
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
